// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu6e4JS7e6OoZ3Q2kOVK5FwT2fhQMJmLw',
    appId: '1:697950556507:web:2f3caaacdf037829fa4a7e',
    messagingSenderId: '697950556507',
    projectId: 'student-helper-mrk',
    authDomain: 'student-helper-mrk.firebaseapp.com',
    storageBucket: 'student-helper-mrk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLCrooHSuQfcQF3VxyfeBUCASwoCkbGs',
    appId: '1:697950556507:android:8e59d9c8a4da8855fa4a7e',
    messagingSenderId: '697950556507',
    projectId: 'student-helper-mrk',
    storageBucket: 'student-helper-mrk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgmVQqd7PtAUDb3zu-5ZO9E9pPSifXTeo',
    appId: '1:697950556507:ios:024921a0c41b2862fa4a7e',
    messagingSenderId: '697950556507',
    projectId: 'student-helper-mrk',
    storageBucket: 'student-helper-mrk.firebasestorage.app',
    iosBundleId: 'com.example.studentHelper',
  );
}
